apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf
  namespace: default
spec:
  type: NodePort
  selector:
    app: stirling-pdf
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30081  # optional, Kubernetes can auto-assign if omitted
